# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
run:
  tests: false

linters:
  enable-all: true
  disable:
   - godot
   - gci
   - exhaustivestruct

linters-settings:
  gocritic:
    enabled-tags:
      - style
      - experimental
      - performance
      - diagnostic
      - opinionated

service:
  golangci-lint-version: 1.41.x

issues:
  exclude:
    - use MixedCaps in package name
