// Generated by tron. Place config helpers here.

package config

import (
	"log"

	"github.com/loghole/tron/rtconfig"
)

// GetExampleValue returns ExampleValue from config.
func GetExampleValue() string {
	return rtconfig.GetString(ExampleValue)
}

// WatchExampleValue starts watching ExampleValue change.
func WatchExampleValue() {
	_ = rtconfig.WatchVariable(ExampleValue, func(oldValue, newValue rtconfig.Value) {
		log.Printf("old example value = %s, new example value = %s", oldValue.String(), newValue.String())
	})
}
