// Generated by tron. Place config helpers here.

package config

/*
// GetExampleValue returns ExampleValue from config.
func GetExampleValue() string {
	return config.GetString(ExampleValue)
}

// WatchExampleValue starts watching ExampleValue change.
func WatchExampleValue() {
	_ = config.WatchVariable(ExampleValue, func(oldValue, newValue config.Value) {
		log.Printf("old example value = %s, new example value = %s", oldValue.String(), newValue.String())
	})
}
*/
