// Generated by tron. Place config helpers here.
package config

import (
	"github.com/spf13/viper"
)

// GetExampleValue returns ExampleValue from viper config.
func GetExampleValue() string {
	return viper.GetString(ExampleValue)
}
