// Code generated by tron v0.17.2. DO NOT EDIT.
package config

const (
	ExampleValue       = "example_value"
	JaegerSamplerParam = "jaeger_sampler_param"
	JaegerSamplerType  = "jaeger_sampler_type"
)
