env:
  - LOGGER_LEVEL=info
  - LOGGER_COLLECTOR_ADDR=
  - LOGGER_DISABLE_STDOUT=false
  - JAEGER_ADDR=127.0.0.1:6831
  - SERVICE_PORT_HTTP=8080
  - SERVICE_PORT_PORT=8081
  - SERVICE_PORT_ADMIN=8082
  

