LOGGER_LEVEL: info
LOGGER_COLLECTOR_ADDR: ""
LOGGER_DISABLE_STDOUT: false
JAEGER_ADDR: ""
JAEGER_SAMPLER_TYPE: const
JAEGER_SAMPLER_PARAM: 0.5
SERVICE_PORT_HTTP: 8080
SERVICE_PORT_GRPC: 8081
SERVICE_PORT_ADMIN: 8082

# Place default config values here
EXAMPLE_VALUE: example_value
