run:
  tests: false
  skip-dirs:
    - scripts
linters:
  enable-all: true
  disable:
    - godot
    - gci
linters-settings:
  gocritic:
    enabled-tags:
      - style
      - experimental
      - performance
      - diagnostic
      - opinionated