run:
  tests: false
linters:
  enable-all: true
  disable:
    - godot
    - gci
    - exhaustivestruct
    - ireturn
    - varnamelen
linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
  gocritic:
    enabled-tags:
      - style
      - experimental
      - performance
      - diagnostic
      - opinionated
service:
  golangci-lint-version: 1.41.x
issues:
  include:
    - EXC0002
