package templates

import (
	"strings"

	"github.com/loghole/tron/cmd/tron/internal/helpers"
	"github.com/loghole/tron/cmd/tron/internal/models"
)

type ConfigData struct {
	Values []ConfigValue
}

type ConfigValue struct {
	Name string
	Key  string
}

func NewConfigValue(key string) ConfigValue {
	name := models.GoNameRexp.ReplaceAllString(key, "")
	name = models.FirstDigitsRexp.ReplaceAllString(name, "")
	name = helpers.UpperCamelCase(name)

	return ConfigValue{Name: name, Key: strings.ToLower(key)}
}

const ConfigConstTemplate = `// Code generated by tron. DO NOT EDIT.
package config

const (
	{{ range $v := .Values -}}
	{{ $v.Name }} = "{{ $v.Key }}"
	{{ end }}
)
`

const ConfigTemplate = `// Code generated by tron. Place config helpers here.
package config

import (
	"github.com/spf13/viper"
)

// GetExampleValue returns ExampleValue from viper config.
func GetExampleValue() string {
	return viper.GetString(ExampleValue)
}
`
