package templates

const TronMK = `# Code generated by tron. DO NOT EDIT.
# You can extend or override anything in ./Makefile

LOCAL_BIN:=$(CURDIR)/bin

.PHONY: .generate
.generate:
	tron generate --proto=api

# generate code from proto and config
.PHONY: generate
generate: bin-deps pb-deps .generate

# generate code from proto but without downloading proto deps
.PHONY: fast-generate
fast-generate: .generate

# install proto dependencies
.PHONY: pb-deps
pb-deps:

.PHONY: .bin-deps
.bin-deps:
	$(info #Installing binary dependencies...)
	GOBIN=$(LOCAL_BIN) go install github.com/gogo/protobuf/protoc-gen-gofast
	GOBIN=$(LOCAL_BIN) go install github.com/utrack/clay/v2/cmd/protoc-gen-goclay

bin-deps: .bin-deps

`

const Makefile = `include tron.mk
`
