// Code generated by protoc-gen-tron. DO NOT EDIT.
// source: example/api/strings/v1/strings.proto

package stringsV1

import (
	"context"
	"embed"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/loghole/tron/transport"
	"google.golang.org/grpc"
)

//go:embed strings.swagger.json
var swagger embed.FS

// StringsServiceDesc is description for the StringsServer.
type StringsServiceDesc struct {
	svc StringsServer
}

func NewStringsServiceDesc(s StringsServer) transport.ServiceDesc {
	return &StringsServiceDesc{svc: s}
}

func (d *StringsServiceDesc) RegisterGRPC(s *grpc.Server) {
	RegisterStringsServer(s, d.svc)
}

func (d *StringsServiceDesc) RegisterHTTP(mux *runtime.ServeMux) {
	RegisterStringsHandlerServer(context.Background(), mux, d.svc)
}

func (d *StringsServiceDesc) SwaggerDef() []byte {
	b, _ := swagger.ReadFile("strings.swagger.json")

	return b
}
