// Code generated by protoc-gen-tron. DO NOT EDIT.
// source: example/api/strings/v1/strings.proto

package stringsV1

import (
	"context"
	"embed"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/loghole/tron/transport"
	"google.golang.org/grpc"
)

//go:embed strings.swagger.json
var swagger embed.FS

// StringsAPIServiceDesc is description for the StringsAPIServer.
type StringsAPIServiceDesc struct {
	svc StringsAPIServer
}

func NewStringsAPIServiceDesc(s StringsAPIServer) transport.ServiceDesc {
	return &StringsAPIServiceDesc{svc: s}
}

func (d *StringsAPIServiceDesc) RegisterGRPC(s *grpc.Server) {
	RegisterStringsAPIServer(s, d.svc)
}

func (d *StringsAPIServiceDesc) RegisterHTTP(mux *runtime.ServeMux) {
	RegisterStringsAPIHandlerServer(context.Background(), mux, d.svc)
}

func (d *StringsAPIServiceDesc) SwaggerDef() []byte {
	b, _ := swagger.ReadFile("strings.swagger.json")

	return b
}
