// Code generated by tron v0.5.2-1-gc6d9e91. DO NOT EDIT.

package stringsV1

import (
	context "context"

	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	grpc "google.golang.org/grpc"

	transport "github.com/loghole/tron/transport"
)

// StringsServiceDesc is description for the StringsServer.
type StringsServiceDesc struct {
	svc StringsServer
}

func NewStringsServiceDesc(i StringsServer) transport.ServiceDesc {
	return &StringsServiceDesc{svc: i}
}

func (d *StringsServiceDesc) RegisterGRPC(s *grpc.Server) {
	RegisterStringsServer(s, d.svc)
}

func (d *StringsServiceDesc) RegisterHTTP(mux *runtime.ServeMux) {
	RegisterStringsHandlerServer(context.Background(), mux, d.svc)
}

func (d *StringsServiceDesc) SwaggerDef() []byte {
	return []byte(`{
  "swagger": "2.0",
  "info": {
    "title": "strings.proto",
    "version": "version not set"
  },
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/api/v1/strings/info": {
      "get": {
        "operationId": "Strings_GetInfo",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/types.v1.String"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/google.rpc.Status"
            }
          }
        },
        "parameters": [
          {
            "name": "str",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ],
        "tags": [
          "Strings"
        ]
      }
    },
    "/api/v1/strings/upper/{str}": {
      "get": {
        "summary": "Method to upper",
        "operationId": "Strings_ToUpper",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/types.v1.String"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/google.rpc.Status"
            }
          }
        },
        "parameters": [
          {
            "name": "str",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "Strings"
        ]
      }
    }
  },
  "definitions": {
    "google.protobuf.Any": {
      "type": "object",
      "properties": {
        "typeUrl": {
          "type": "string"
        },
        "value": {
          "type": "string",
          "format": "byte"
        }
      }
    },
    "google.rpc.Status": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "details": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/google.protobuf.Any"
          }
        }
      }
    },
    "types.v1.String": {
      "type": "object",
      "properties": {
        "str": {
          "type": "string"
        }
      }
    }
  }
}
`)
}
