// Generated by protoc-gen-tron.

package stringsV1

import (
	"github.com/loghole/tron/transport"

	stringsV1 "example/pkg/api/strings/v1"
)

type Implementation struct {
	stringsV1.UnimplementedStringsServer
}

func NewImplementation() *Implementation {
	return &Implementation{}
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *Implementation) GetDescription() transport.ServiceDesc {
	return stringsV1.NewStringsServiceDesc(i)
}
