// Generated by protoc-gen-tron.

package stringsV1

import (
	"context"
	"errors"

	stringsV1 "github.com/loghole/tron/example/pkg/api/strings/v1"
)

func (i *Implementation) ToUpper(
	ctx context.Context,
	req *stringsV1.ToUpperReq,
) (*stringsV1.ToUpperResp, error) {
	return nil, errors.New("unimplemented")
}
