// Generated by protoc-gen-tron.

package stringsV1

import (
	"context"
	"errors"

	typesV1 "example/pkg/api/types/v1"
)

func (i *Implementation) ToUpper(
	ctx context.Context,
	req typesV1.String,
) (typesV1.String, error) {
	return errors.New("unimplemented")
}
