// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: strings.proto

package v1

import (
	"context"
	desc "example/pkg/v1"

	"github.com/pkg/errors"
)

func (i *Implementation) GetInfo(ctx context.Context, req *desc.String) (*desc.String, error) {
	return nil, errors.New("GetInfo not implemented")
}
