// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: strings.proto

package v1

import (
	"context"
	desc "example/pkg/v1"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestImplementation_GetInfo(t *testing.T) {
	api := NewStrings()
	_, err := api.GetInfo(context.Background(), &desc.String{})

	require.NotNil(t, err)
	require.Equal(t, "GetInfo not implemented", err.Error())
}
