// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: strings.proto

package v1

import (
	"context"
	"testing"

	desc "github.com/loghole/collector/pkg/v1"
	"github.com/stretchr/testify/require"
)

func TestImplementation_ToUpper(t *testing.T) {
	api := NewStrings()
	_, err := api.ToUpper(context.Background(), &desc.String{})

	require.NotNil(t, err)
	require.Equal(t, "ToUpper not implemented", err.Error())
}
