# More info on config here: https://github.com/golangci/golangci-lint#config-file
run:
  tests: false
linters:
  enable-all: true
  disable:
    - godot
    - gci
    - nolintlint
    - wrapcheck
    - exhaustivestruct
    - forbidigo
    - revive
    - cyclop
    - gomoddirectives # need root lib constants.
linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
  gocritic:
    enabled-tags:
      - style
      - experimental
      - performance
      - diagnostic
      - opinionated
service:
  golangci-lint-version: 1.41.x
