// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: strings.proto

package stringsV1

import (
	"context"
	typesV1 "example/pkg/types/v1"

	"github.com/pkg/errors"
)

func (i *Implementation) GetInfo(ctx context.Context, req *typesV1.String) (*typesV1.String, error) {
	return nil, errors.New("GetInfo not implemented")
}
