// Code generated by tron. You must modify it.

package stringsV1

import (
	context "context"
	errors "errors"
	stringsV1 "example/pkg/strings/v1"
	typesV1 "example/pkg/types/v1"
)

func (i *Implementation) List(
	ctx context.Context,
	req *typesV1.String,
) (resp *stringsV1.ListResp, err error) {
	return nil, errors.New("method List unimplemented")
}
