// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: strings.proto

package stringsV1

import (
	desc "example/pkg/strings/v1"
	"github.com/loghole/tron/transport"
)

type Implementation struct{
	desc.UnimplementedStringsServer
}

// NewStrings create new Implementation
func NewStrings() *Implementation {
	return &Implementation{}
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *Implementation) GetDescription() transport.ServiceDesc {
	return desc.NewStringsServiceDesc(i)
}
