// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: strings.proto

package strings

import (
	"context"

	desc "github.com/loghole/tron/example/pkg/strings/v1"
	"github.com/pkg/errors"
)

func (i *Implementation) ToUpper(ctx context.Context, req *desc.String) (*desc.String, error) {
	return nil, errors.New("ToUpper not implemented")
}
