// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: strings.proto

package stringsV1

import (
	"context"
	typesV1 "example/pkg/types/v1"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestImplementation_ToUpper(t *testing.T) {
	api := NewStrings()
	_, err := api.ToUpper(context.Background(), &typesV1.String{})

	require.NotNil(t, err)
	require.Equal(t, "ToUpper not implemented", err.Error())
}
