# More info on config here: https://github.com/golangci/golangci-lint#config-file
run:
  tests: false
linters:
  enable-all: true
  disable:
    - godot
    - gci
    - nolintlint
    - wrapcheck
    - exhaustivestruct
    - forbidigo
    - revive
    - cyclop
    - varnamelen
linters-settings:
  gocritic:
    enabled-tags:
      - style
      - experimental
      - performance
      - diagnostic
      - opinionated
