name: "lint and test"
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  golint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49

  gotest:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      TZ: Europe/Moscow
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        run: make test
