name: "lint and test"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  golangci-lint:
    name: lint
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.21'
          check-latest: true
          cache: true
      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          args: --verbose

  gotest:
    name: test
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v5
      with:
        go-version: 1.21.x
        cache: true
    - run: make test
