name: "lint and test"
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  golint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.0

  gotest:
    name: test
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Moscow
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: make test
